# Generated by Django 5.0.3 on 2025-12-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='pet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pets/'),
        ),
        migrations.AddField(
            model_name='pet',
            name='image_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('lost', 'Lost'), ('found', 'Found'), ('available', 'Available')], default='available', max_length=20),
        ),
    ]
