# Generated by Django 5.0.3 on 2025-12-08 08:39

import django.db.models.deletion
import pets.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_pet_contact_phone_pet_image_pet_image_hash_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('owner_approved', 'Owner Approved'), ('owner_rejected', 'Owner Rejected'), ('rescuer_confirmed', 'Rescuer Confirmed')], default='pending', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=pets.models.default_expiry)),
                ('found_pet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='found_matches', to='pets.pet')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_requests', to='pets.pet')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
