# Generated by Django 5.0.3 on 2025-12-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_pet_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('lost', 'Lost'), ('found', 'Found'), ('adoption', 'Available for Adoption')], default='lost', max_length=20),
        ),
    ]
