# Generated by Django 5.0.3 on 2025-12-20 12:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0008_alter_pet_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='animal_condition',
            field=models.CharField(choices=[('healthy', 'Healthy'), ('injured', 'Injured'), ('sick', 'Sick'), ('critical', 'Critical')], default='healthy', max_length=20),
        ),
        migrations.AddField(
            model_name='pet',
            name='last_seen_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pet',
            name='medical_attention_needed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pet',
            name='report_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
