# Generated by Django 5.0.3 on 2025-12-15 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('adopter', 'Adopter'), ('rescuer', 'Rescuer'), ('pet_owner', 'Pet Owner'), ('admin', 'Admin')], default='adopter', help_text='Select your role in the pet rescue community', max_length=20),
        ),
    ]
