# Generated by Django 5.0.3 on 2025-12-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_otp_remove_profile_otp_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('adopter', 'Adopter'), ('rescuer', 'Rescuer'), ('pet_owner', 'Pet Owner')], default='adopter', help_text='Select your role in the pet rescue community', max_length=20),
        ),
    ]
